"""initial_schema

Revision ID: e60ad1eb0a30
Revises:
Create Date: 2026-02-26 15:13:24.706867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e60ad1eb0a30"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dlq_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=False),
        sa.Column("event_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("error_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'FAILED'"), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("last_error_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dlq_records")),
        sa.UniqueConstraint("event_id", name=op.f("uq_dlq_records_event_id")),
    )
    op.create_index("ix_dlq_records_delivery_id", "dlq_records", ["delivery_id"], unique=False)
    op.create_index("ix_dlq_records_status", "dlq_records", ["status"], unique=False)
    op.create_table(
        "repo_config",
        sa.Column("repo_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_full_name", sa.Text(), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("repo_id", name=op.f("pk_repo_config")),
    )
    op.create_table(
        "webhook_delivery",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=False),
        sa.Column("event_name", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_full_name", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'RECEIVED'"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_delivery")),
        sa.UniqueConstraint("delivery_id", name=op.f("uq_webhook_delivery_delivery_id")),
    )
    op.create_table(
        "developer_profile",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("github_login", sa.Text(), nullable=False),
        sa.Column(
            "skills", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("max_capacity", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("open_assignments", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repo_config.repo_id"],
            name=op.f("fk_developer_profile_repo_id_repo_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_developer_profile")),
        sa.UniqueConstraint("repo_id", "github_login", name="uq_dev_profile_repo_login"),
    )
    op.create_index(
        "ix_dev_profile_repo_open_assignments", "developer_profile", ["repo_id", "open_assignments"], unique=False
    )
    op.create_table(
        "issue_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.BigInteger(), nullable=False),
        sa.Column("issue_node_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("labels", postgresql.ARRAY(sa.Text()), server_default=sa.text("ARRAY[]::TEXT[]"), nullable=False),
        sa.Column("author_login", sa.Text(), nullable=False),
        sa.Column("issue_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issue_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repo_config.repo_id"], name=op.f("fk_issue_snapshot_repo_id_repo_config"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issue_snapshot")),
        sa.UniqueConstraint("event_id", name=op.f("uq_issue_snapshot_event_id")),
    )
    op.create_index(
        "ix_issue_snapshot_repo_issue_time",
        "issue_snapshot",
        ["repo_id", "issue_number", sa.literal_column("snapshot_at DESC")],
        unique=False,
    )
    op.create_table(
        "triage_decision",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("predicted_priority", sa.Text(), nullable=True),
        sa.Column("predicted_category", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("selected_assignee_login", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("patch_state", sa.Text(), server_default=sa.text("'DECIDED'"), nullable=False),
        sa.Column("patch_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "patch_state IN ('DECIDED','APPLIED','FAILED_RETRY','SKIPPED_DUPLICATE')",
            name=op.f("ck_triage_decision_patch_state"),
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repo_config.repo_id"],
            name=op.f("fk_triage_decision_repo_id_repo_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_triage_decision")),
        sa.UniqueConstraint("event_id", name=op.f("uq_triage_decision_event_id")),
    )
    op.create_index("ix_triage_decision_repo_issue_time", "triage_decision", ["repo_id", "issue_number"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_triage_decision_repo_issue_time", table_name="triage_decision")
    op.drop_table("triage_decision")
    op.drop_index("ix_issue_snapshot_repo_issue_time", table_name="issue_snapshot")
    op.drop_table("issue_snapshot")
    op.drop_index("ix_dev_profile_repo_open_assignments", table_name="developer_profile")
    op.drop_table("developer_profile")
    op.drop_table("webhook_delivery")
    op.drop_table("repo_config")
    op.drop_index("ix_dlq_records_status", table_name="dlq_records")
    op.drop_index("ix_dlq_records_delivery_id", table_name="dlq_records")
    op.drop_table("dlq_records")
    # ### end Alembic commands ###
